export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_TECHNOLOGY = "ADD_TECHNOLOGY";
export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY";
export const INCORRECT_TECHNOLOGY = "INCORRECT_TECHNOLOGY";
export const CONTACTS_LOADED = "CONTACTS_LOADED";