import { ContactsListDTO } from './ContactsList';
export const contactsList: ContactsListDTO[] = [
  {
    birthDate: '1995-10-17',
    email: 'andrii.didovych@sombrainc.com',
    firstName: 'Andrii',
    id: 200,
    lastName: 'Didovych',
    office: 'LV',
    personalEmail: 'andrii.didovych@gmail.com',
    phoneOne: '098 709 24 60',
    phoneTwo: null,
    position: 'Trainee Java developer',
    skype: 'live:andrii.didovych',
  },
  {
    birthDate: '1996-09-16',
    email: 'andrii.ostryzhniuk@sombrainc.com',
    firstName: 'Andrii',
    id: 132,
    lastName: 'Ostryzhniuk',
    office: 'IF',
    personalEmail: 'andrii.ostryzhniuk@gmail.com',
    phoneOne: '099 376 85 21',
    phoneTwo: '096 730 32 98',
    position: 'Strong Junior Java developer',
    skype: 'ostryzhnykandriy',
  },
  {
    birthDate: '1989-07-05',
    email: 'anna.fedorus@sombrainc.com',
    firstName: 'Anna',
    id: 35,
    lastName: 'Fedorus',
    office: 'LV',
    personalEmail: 'annfedorus@gmail.com',
    phoneOne: '063 454 80 34',
    phoneTwo: null,
    position: 'HR Coordinator',
    skype: 'fedorusanna',
  },
  {
    birthDate: '1994-09-25',
    email: 'anna.lotovska@sombrainc.com',
    firstName: 'Anna',
    id: 171,
    lastName: 'Lotovska',
    office: 'LV',
    personalEmail: 'ann.lotovska@gmail.com',
    phoneOne: '099 094 24 99',
    phoneTwo: null,
    position: 'Sales assistant',
    skype: 'annalotovska',
  },
  {
    birthDate: '1986-10-22',
    email: 'artem.korchevyi@sombrainc.com',
    firstName: 'Artem',
    id: 184,
    lastName: 'Korchevyi',
    office: 'IF',
    personalEmail: 'artem.korchevy@gmail.com',
    phoneOne: '066 584 63 41',
    phoneTwo: null,
    position: 'Middle QA Automation',
    skype: 'live:antracot',
  },
  {
    birthDate: '1991-07-01',
    email: 'bohdamyr@sombrainc.com',
    firstName: 'Bohdamyr',
    id: 28,
    lastName: 'Stefaniuk',
    office: 'IF',
    personalEmail: 'levovi4@gmail.com',
    phoneOne: '0633094432',
    phoneTwo: '',
    position: 'Middle Java developer',
    skype: 'theevilsscream',
  },
  {
    birthDate: '1994-06-01',
    email: 'bohdan.levkovych@sombrainc.com',
    firstName: 'Bohdan',
    id: 96,
    lastName: 'Levkovych',
    office: 'LV',
    personalEmail: 'fnx@ukr.net',
    phoneOne: '0636514491',
    phoneTwo: null,
    position: 'Middle Java developer',
    skype: 'vasul.petroivanstepan',
  },
  {
    birthDate: '1996-05-27',
    email: 'bohdan.savshak@sombrainc.com',
    firstName: 'Bohdan',
    id: 141,
    lastName: 'Savshak',
    office: 'LV',
    personalEmail: 'savshakbohdan@gmail.com',
    phoneOne: '0987243261',
    phoneTwo: null,
    position: 'Strong Junior Java developer',
    skype: 'live:savshak',
  },
  {
    birthDate: '1995-03-31',
    email: 'bohdan.smachylo@sombrainc.com',
    firstName: 'Bohdan',
    id: 13,
    lastName: 'Smachylo',
    office: 'LV',
    personalEmail: 'bsmachylo86@gmail.com',
    phoneOne: '097 642 66 50',
    phoneTwo: '0635582273',
    position: 'Middle Java developer',
    skype: 'bogdan9812',
  },
  {
    birthDate: '1986-07-26',
    email: 'bogdan.vesylivskyy@sombrainc.com',
    firstName: 'Bohdan',
    id: 196,
    lastName: 'Vesylivskyy',
    office: 'LV',
    personalEmail: 'vesylivskyy@gmail.com',
    phoneOne: '380 685 01 26',
    phoneTwo: null,
    position: 'Word Press developer',
    skype: 'bvesyliv',
  },
  {
    birthDate: '1994-08-04',
    email: 'igor.bardyuk@sombrainc.com',
    firstName: 'Ihor',
    id: 91,
    lastName: 'Bardiuk',
    office: 'IF',
    personalEmail: 'igor.igruk@gmail.com',
    phoneOne: '0500267637',
    phoneTwo: null,
    position: 'Strong Junior Java developer',
    skype: 'igruk.igor1',
  },
  {
    birthDate: '1996-04-19',
    email: 'ihor.bilobran@sombrainc.com',
    firstName: 'Ihor',
    id: 168,
    lastName: 'Bilobran',
    office: 'LV',
    personalEmail: 'ihor.bilobran@gmail.com',
    phoneOne: '067 800 40 41',
    phoneTwo: null,
    position: 'Junior Front-end developer',
    skype: 'ihor.bilobran96',
  },
  {
    birthDate: '1995-11-24',
    email: 'ihor.cherepakha@sombrainc.com',
    firstName: 'Ihor',
    id: 195,
    lastName: 'Cherepakha',
    office: 'IF',
    personalEmail: 'cherepakha@yahoo.com',
    phoneOne: '0960169647',
    phoneTwo: null,
    position: 'Trainee Front-end developer',
    skype: 'live:cherepakha_3',
  },
  {
    birthDate: '1996-05-26',
    email: 'iryna.bohaichuk@sombrainc.com',
    firstName: 'Iryna',
    id: 112,
    lastName: 'Bohaichuk',
    office: 'LV',
    personalEmail: 'ibogaychuk96@gmail.com',
    phoneOne: '093 534 76 89',
    phoneTwo: '068 009 62 41',
    position: 'Junior Recruiter',
    skype: 'live:613950dd8e3bff33',
  },
  {
    birthDate: '1990-10-19',
    email: 'iryna.dovhanyk@sombrainc.com',
    firstName: 'Iryna',
    id: 54,
    lastName: 'Dovhanyk',
    office: 'LV',
    personalEmail: 'iravesna@gmail.com',
    phoneOne: '097 765 74 67',
    phoneTwo: '063 177 92 26',
    position: 'Head of Finance and Legal',
    skype: 'iravesna19',
  },
  {
    birthDate: '1990-01-16',
    email: 'iryna.kyryleiza@sombrainc.com',
    firstName: 'Iryna',
    id: 151,
    lastName: 'Kyryleyza',
    office: 'LV',
    personalEmail: 'iryna3339@gmail.com',
    phoneOne: '0975245441',
    phoneTwo: null,
    position: 'Accountant Assistant',
    skype: 'live:iryna3339',
  },
  {
    birthDate: '1996-09-12',
    email: 'ivan.arabchuk@sombrainc.com',
    firstName: 'Ivan',
    id: 98,
    lastName: 'Arabchuk',
    office: 'IF',
    personalEmail: 'iVankoarabchuk@gmail.com',
    phoneOne: '066 041 89 82',
    phoneTwo: null,
    position: 'Strong Junior Java developer',
    skype: 'live:ivanarabchuk',
  },
  {
    birthDate: '1993-03-17',
    email: 'ivan.koss@sombrainc.com',
    firstName: 'Ivan',
    id: 65,
    lastName: 'Kos',
    office: 'IF',
    personalEmail: 'ivan.koss.b@gmail.com',
    phoneOne: '0687092435',
    phoneTwo: '0669957948',
    position: 'Middle Front-end developer',
    skype: 'kos_vanja',
  },
  {
    birthDate: '1996-06-17',
    email: 'juliia.mykytyn@sombrainc.com',
    firstName: 'Juliia',
    id: 191,
    lastName: 'Mykytyn',
    office: 'LV',
    personalEmail: 'juliamykytyn17@gmail.com',
    phoneOne: '068  85 4  50 84',
    phoneTwo: null,
    position: 'Accountant Assistant',
    skype: 'live:9516858696715d3f',
  },
  {
    birthDate: '1987-07-02',
    email: 'kateryna.dzigua@sombrainc.com',
    firstName: 'Kateryna',
    id: 161,
    lastName: 'Dzigua',
    office: 'LV',
    personalEmail: 'katrin.dzigua@gmail.com',
    phoneOne: '093 673 81 98',
    phoneTwo: null,
    position: 'UX/UI Designer',
    skype: 'katrin.dzigua',
  }
];

